### ISSUE TITLE
Time for releasing dataset and codes.

### ISSUE THREAD

**Issue by Michel-liu** [CHELSEA234/HiFi_IFDL#1]
Interesting work! May I ask about your plan for releasing the dataset and codes?

**Comment by LonelyPlanetIoT** [comment]
It is a interesting work but I wanna konw How many computing resources were used .

**Comment by Pudge-tao** [comment]
很好，啥时候提供代码和预训练模型验证一下效果如何

**Comment by laiyingxin2** [comment]
Same question

**Comment by 85zhanghao** [comment]
Same question

**Comment by CHELSEA234** [comment]
@Michel-liu @LonelyPlanetIoT @Pudge-tao @laiyingxin2 
Could you please refer to the current version source code first? Let me know what else is needed.
We are currently working on organizing the dataset and source code, they will come soon.

**Comment by laiyingxin2** [comment]
When the dataset will be released

**Comment by ORainn** [comment]
Looking forward to the release of source code and dataset.

**Comment by Stitchsong** [comment]
Good work! I want to ask when to release the dataset and codes.

**Comment by CHELSEA234** [comment]
I think you guys can check the dataset a bit.
