### ISSUE TITLE
about  the  train  code

### ISSUE THREAD

**Issue by 85zhanghao** [CHELSEA234/HiFi_IFDL#10]
When I run the `train.sh` command, I noticed that different datasets require different txt files containing the image lists. Can you provide the corresponding txt files?

**Comment by 85zhanghao** [comment]
The error message that appears is as follows:
FileNotFoundError: [Errno 2] No such file or directory: '/user/guoxia11/cvlshare/cvl-guoxia11/IMDL/REAL/authentic.txt'

**Comment by Samarium-Z** [comment]
I have the same problem with @85zhanghao.Could you please provide the corresponding txt files?

**Comment by GWZ313** [comment]
I have also encountered the same problem. Can you provide the corresponding files? Thank you, my email is 1608194273@qq.com

**Comment by CHELSEA234** [comment]
@85zhanghao @Samarium-Z @GWZ313 sorry for the late reply. you can find txt file in this [link](https://drive.google.com/drive/folders/1OIUv7OGxfAyerMnmKvrNnN_5CmIDcNxo?usp=sharing), which is just a list of name for all training images.

**Comment by Samarium-Z** [comment]
Thank you for your assistance~

CHELSEA234 ***@***.***> 于2023年10月12日周四 00:56写道：
