### ISSUE TITLE
CopyMove Images does not have the Groundtruth mask images and Pristine Images

### ISSUE THREAD

**Issue by SoumyaroopNandi** [CHELSEA234/HiFi_IFDL#11]
Good job on creating the dataset. Can you release the groundtruth mask images and original pristine images for the CopyMove images in Dataset Link? There are only 100K forged images in the CopyMove folder.

**Comment by CHELSEA234** [comment]
Hi @SoumyaroopNandi, I am Xiao. We used to work as colleagues at ISI, I hope everything goes well on your end.
In fact, the fastest way for you is to take the label of Rex's BusterNet paper, I directly took his public dataset to compose the dataset in this paper. Let me know what else I can help you, and please feel free to reopen this issue.
