### ISSUE TITLE
google colab

### ISSUE THREAD

**Issue by Nardin-Algarguri** [CHELSEA234/HiFi_IFDL#12]
Are there any plans for a google colab notebook, with my GPU and the sizes of the datasets it's very hard to run it on my local machine, if yes, when can we expect it? Thank you!

**Comment by CHELSEA234** [comment]
@Nardin-Algarguri, I have updated a new [section](https://github.com/CHELSEA234/HiFi_IFDL#quick-usage-on-manipulation-localization) code, please let me know if you can play around with it.

**Comment by CHELSEA234** [comment]
Please feel free to reopen this issue, if you need colab assistance.
