### ISSUE TITLE
RuntimeError about GPU 

### ISSUE THREAD

**Issue by 311311y** [CHELSEA234/HiFi_IFDL#17]
hello,Thank you for your work.
I have a trouble when I run bash HiFi_Net_loc.sh
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
what should I do to make it correct，thank you so much

**Comment by 7summer** [comment]
hello, I meet the same of problem also today.

you need modify the file HiFi_Net_loc.sh.

```bash
CUDA_NUM=0
CUDA_VISIBLE_DEVICES=$CUDA_NUM python HiFi_Net_loc.py 
```
This CUDA_NUM needs to be set according to the actual situation of your computer

You need to use the cmd window, use the command nvidia-smi, get the number of GPU on you computer, the number of GPU on my computer is 1, so my CUDA_NUM is set to 0, CUDA_VISIBLE_DEVICES means the GPU number

**Comment by 7summer** [comment]
If you have a GPU number of 2 and your GPU number is 0 or 1

**Comment by 311311y** [comment]
@7summer Thank you so much for your answer
