### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by shunlibiyela** [CHELSEA234/HiFi_IFDL#21]
Can you provide the list and ground truth of the CopyMove dataset, please? I attempted to download the BusterNet dataset, but without success.
Additionally,I didn't see datasets for splice, inpainting, STYL2, and STYL3 in the datasets you provided. Could you please provide them as well?.
Thank you very much.

**Comment by 7summer** [comment]
you can download the dataset you need via the [link](https://drive.google.com/drive/folders/1fwBEmW30-e0ECpCNNG3nRU6I9OqJfMAn).

**Comment by CHELSEA234** [comment]
@jinjinw thank you very much for attending our work. In fact, STYL2 and STYL3 can be any images generated from the official GitHubs from styleGAN2 and styleGAN3.
