### ISSUE TITLE
 I test the model by HiFi_Net.py,but got ped_mask.png which is all black and the confidence is outputed correctly. Can u tell me the reason?

### ISSUE THREAD

**Issue by SherlockHua1995** [CHELSEA234/HiFi_IFDL#22]
THANKS FOR YOUR WONDERFUL WORK.
I test the model by HiFi_Net.py,but got ped_mask.png which is all black and the confidence is outputed correctly.
Can u tell me the reason?

**Comment by CHELSEA234** [comment]
can you refer this issue: https://github.com/CHELSEA234/HiFi_IFDL/issues/19#issuecomment-1803306172
