### ISSUE TITLE
   about this error: if  len(cuda_list) == 1: TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Cococc2** [CHELSEA234/HiFi_IFDL#24]
![image](https://github.com/CHELSEA234/HiFi_IFDL/assets/119996653/67e59733-457d-433a-9beb-0d70c7f6f0d1)
How do I fix this? My cuda is available.
thanks for your answer!  :)

**Comment by 311311y** [comment]
Can you share how to fix it？I also had the same problem
