### ISSUE TITLE
Problem with vallist.txt

### ISSUE THREAD

**Issue by 7summer** [CHELSEA234/HiFi_IFDL#26]
Hello, thank for your response.
I'm executing in the cmd window.

```bash
CUDA_NUM=0
CUDA_VISIBLE_DEVICES=$CUDA_NUM python HiFi_Net_loc.py 
```

As a result, an error is reported in the program.

```bash
  File "F:\MachineLearning\HiFi_IFDL\utils\load_edata.py", line 109, in __init__
    with open(join(ddir, 'vallist.txt')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/user/guoxia11/cvl/semi
_supervise_local/2021/05_25_SCCM/Dataset/finetune_dataset/columbia/vallist.txt'
```

I think the error is due to the fact that there is no vallist file under that path, I want to know how to get the file, thanks for the answer.

**Comment by 311311y** [comment]
I have the same problem ，No such file or directory: '/user/guoxia11/cvl/semi_supervise_local/2021/05_25_SCCM/Dataset/finetune_dataset/columbia/vallist.txt'
I downloaded the Columbia dataset，I think we should first modify the path to your Validation set，and I want to know vallist.txt specific content
![微信截图_20231204164843](https://github.com/CHELSEA234/HiFi_IFDL/assets/149998055/2535f19c-8ae9-40ce-ac72-ac863c87e622)

**Comment by 311311y** [comment]
I have the same problem ，No such file or directory: '/user/guoxia11/cvl/semi_supervise_local/2021/05_25_SCCM/Dataset/finetune_dataset/columbia/vallist.txt'
I downloaded the Columbia dataset，I think we should first modify the path to your Validation set，and I want to know vallist.txt specific content

**Comment by CHELSEA234** [comment]
@7summer @311311y 
I have update the [detection section](https://github.com/CHELSEA234/HiFi_IFDL?tab=readme-ov-file#usage-on-manipulation-localization-eg-columbia-coverage-casia-nist16-and-imd2020) and this issue can be solved by downloading tar file of compressed images.
