### ISSUE TITLE
The results verification doesn't match the paper

### ISSUE THREAD

**Issue by kirtons** [CHELSEA234/HiFi_IFDL#27]
Dear author, hello! I find your project very interesting. I downloaded the [qualitative results](https://drive.google.com/drive/folders/1iZp6ciOHSbGq4EsC_AYl7zVK24gBtrd1?usp=sharing) you provided and noticed that some of the predicted results in the images seem to differ from the results posted in your paper. Could you please let me know if there's an issue with my operation?

![iter_99999_step_29_1](https://github.com/CHELSEA234/HiFi_IFDL/assets/43961621/5a7d53eb-bdbe-4b58-91eb-ea3d43a422c5)
this is qualitative result

![image](https://github.com/CHELSEA234/HiFi_IFDL/assets/43961621/5d3acb40-f797-45ad-b36c-63018c8ed122)
this is paper result

**Comment by CHELSEA234** [comment]
Thanks to your question. In fact, I believe I think we use the different weights for visualization in the paper.

**Comment by kirtons** [comment]
Thank you for your response. Your experiments have been very helpful for my recent research. I would like to cite your paper,but I urgently need the weights used in your paper for my comparative experiments. Could you please provide me with the weights used in the paper(table 3.a b c  pre-train model and fine-tuned model)? My email is [mzzhang37@gmail.com](mailto:mzzhang37@gmail.com). I appreciate your assistance.

**Comment by CHELSEA234** [comment]
@kirtons You can simply follow the [section](https://github.com/CHELSEA234/HiFi_IFDL?tab=readme-ov-file#quick-usage-on-manipulation-localization) that already provides pre-trained weights. You can even refer to https://github.com/CHELSEA234/HiFi_IFDL/issues/19#issuecomment-1803306172 for more information

**Comment by kirtons** [comment]
I tested the weights you uploaded（225000.pth,315000.pth）, but the performance still doesn't match the results in the paper. I'm wondering if the model used in the paper hasn't been uploaded. 
![iter_99999_step_3_1](https://github.com/CHELSEA234/HiFi_IFDL/assets/43961621/7f2a83f6-b41f-44cc-83ea-b509e916d006)
the prediction results from the weights you provided.

![image](https://github.com/CHELSEA234/HiFi_IFDL/assets/43961621/641001f4-f3e4-4222-8f2f-40bed9cf4f67)
paper

**Comment by CHELSEA234** [comment]
The weights should produce the visualization as what qualitative result link shows. I think you can double check if you follow the localization section steps.

**Comment by Kelfvin** [comment]
> I tested the weights you uploaded（225000.pth,315000.pth）, but the performance still doesn't match the results in the paper. I'm wondering if the model used in the paper hasn't been uploaded. 
> ![iter_99999_step_3_1](https://github.com/CHELSEA234/HiFi_IFDL/assets/43961621/7f2a83f6-b41f-44cc-83ea-b509e916d006)
> the prediction results from the weights you provided.
> 
> ![image](https://github.com/CHELSEA234/HiFi_IFDL/assets/43961621/641001f4-f3e4-4222-8f2f-40bed9cf4f67)
> paper

I had the same problem as you, did you solve it?
