### ISSUE TITLE
全黑或全白的定位图

### ISSUE THREAD

**Issue by bai-0829** [CHELSEA234/HiFi_IFDL#28]
你好，首先感谢您的开源代码。我在使用的过程中，检测结果出现了全黑的情况，我使用的是“Quick Usage on Detection and Localization:”这个标题下的权重文件和代码。即使是检测代码中“asset”文件夹下的“sample_4.jpg”图片，检测结果也是不正常的，为全白颜色，请问这是什么错误导致的呢？

**Comment by CHELSEA234** [comment]
Can you refer to this link: https://github.com/CHELSEA234/HiFi_IFDL/issues/19#issuecomment-1803306172

**Comment by CHELSEA234** [comment]
@bai-0829 
Hi, could you please let me know if the issue has been solved?
