### ISSUE TITLE
Regarding the issue of paper evaluation data

### ISSUE THREAD

**Issue by CongYep** [CHELSEA234/HiFi_IFDL#30]
![image](https://github.com/CHELSEA234/HiFi_IFDL/assets/49831693/bb559edb-9e0b-4a47-9da4-a016d99b5468)

Regarding the data in Table 3 (a)(b), does the test set include both true and false graphs, or only false graphs?

**Comment by CHELSEA234** [comment]
Can you elaborate on what are true and false graphs?

**Comment by CongYep** [comment]
A true image is a image that has not been tampered with, and a false image is a image that has been tampered with.
真图就是没有经过篡改的图片，假图就是经过篡改的图片。
想问一下训练集是真图和假图都用吗？测试集是仅用假图吗？



---Original---
From: ***@***.***&gt;
Date: Tue, Dec 26, 2023 00:30 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CHELSEA234/HiFi_IFDL] Regarding the issue of paper evaluationdata (Issue #30)




 
Can you elaborate on what are true and false graphs?

**Comment by CHELSEA234** [comment]
@CongYep the evaluation is done on the manipulated image. You cannot get F1 and AUC on the real images. You could go find the test data we used here https://github.com/CHELSEA234/HiFi_IFDL#usage-on-manipulation-localization-eg-columbia-coverage-casia-nist16-and-imd2020

**Comment by CHELSEA234** [comment]
@CongYep in the training, I believe the existing method uses both real and manipulated images. The real images offer real pixels that also help the training.

**Comment by CHELSEA234** [comment]
@CongYep  Please let me know if the confusion has been resolved and feel free to reopen the issue.
