### ISSUE TITLE
How long have you used to train HiFi-Net?

### ISSUE THREAD

**Issue by shunlibiyela** [CHELSEA234/HiFi_IFDL#31]
Hello, I have some questions to ask you. 
How much data did you use for training? Did you use the entire HiFi_IFDL data set?
How long have you used to train HiFi-Net? 
Looking forward to your answer

**Comment by CHELSEA234** [comment]
I think you can find the training epoch in the shared weights checkpoint. Yes, we have used the entire dataset. 
@shunlibiyela
