### ISSUE TITLE
about inpainting.txt

### ISSUE THREAD

**Issue by aries831** [CHELSEA234/HiFi_IFDL#32]
hello!  i notice that inside the inpainting.txt file you gave are some lines really confuse me .   
there are lines ,such as s_1.jpg  ,s_1t.jpg ......   and   also some coco dataset files name  .   i notice that the former is from the coverage dataset.
but for coverage dataset filename :s_1.jpg ...... is a real image  ,and also   coco dataset are real images ,but inpainting.txt  belongs to fake images set .     i think they should not inside the inpating.txt   .

and   can you give the copy_move.txt   and inpating.txt files ?   thank you very much!!!

**Comment by CHELSEA234** [comment]
@aries831 I have updated the txt files. Also, for the copy_move.txt, please go to the busternet paper for their purposed datasets. Your assumption is right, at the begining, we evaluate whether the model can be overfitting the test dataset, so we have included test images in the list.
