### ISSUE TITLE
about F1

### ISSUE THREAD

**Issue by ZXMMD** [CHELSEA234/HiFi_IFDL#33]
![PixPin_2024-03-27_15-51-48](https://github.com/CHELSEA234/HiFi_IFDL/assets/46393405/864f088c-d13a-41a2-bca5-602fc71d1c92)
When you use "average = 'macro'", will the F1 score be inflated higher than normal (average = 'binary')?

**Comment by CHELSEA234** [comment]
@ZXMMD Thank you for this excellent question. In fact, I do not know if 'macro' inflates the performance or not. I chose it as I think it would be the best F1 for the localization scenario. If you refer to this https://www.zhihu.com/question/332571344/answer/2505904685 , you can see macro would compute F1 score for real and manipulated pixels separately, and then get the average. This measures the algorithm performance over predicting both real and manipulated pixels.
