### ISSUE TITLE
关于本地训练模型问题

### ISSUE THREAD

**Issue by kw-yin** [CHELSEA234/HiFi_IFDL#34]
博主您好，很感谢您分享代码与学识。我想要在本地复现，权重与环境均以配置好，可我发现之前的本地训练文件train.py被更新删除了，现在我该如何训练本地模型，“要将预训练模型应用于图像，然后获得结果，请运行 ./data_dir ./viz_eval”，是需要运行之前的train文件嘛。谢谢您的解惑。

**Comment by CHELSEA234** [comment]
> “要将预训练模型应用于图像，然后获得结果，请运行 ./data_dir ./viz_eval”，是需要运行之前的train文件嘛。谢谢您的解惑。

if you just want to apply the model and get the performance, you do not need to run the original train file.
