### ISSUE TITLE
Problem about testing the pre-trained model on CASIA v1 dataset.

### ISSUE THREAD

**Issue by siriusPRX** [CHELSEA234/HiFi_IFDL#35]
I followed the [loc](https://github.com/CHELSEA234/HiFi_IFDL?tab=readme-ov-file#usage-on-manipulation-localization-eg-columbia-coverage-casia-nist16-and-imd2020) and tested the model on CASIA v1 dataset. However, the masks I got are all black. Could you provide some help to solve this problem. Thank you!

**Comment by CHELSEA234** [comment]
@siriusPRX Sorry for the late response, I'm not sure if this problem is solved. Could you please refer to this issue: https://github.com/CHELSEA234/HiFi_IFDL/issues/19#issuecomment-1803306172
