### ISSUE TITLE
Pretty bad results for CASIA dataset with pre-trained weights

### ISSUE THREAD

**Issue by lukesolo** [CHELSEA234/HiFi_IFDL#4]
Tried to evaluate the model on CASIA dataset following [Quick Usage](https://github.com/CHELSEA234/HiFi_IFDL#quick-usage). And I've got pretty bad results, so I'm wondering what I'm doing wrong? According to the paper CASIA dataset should be covered pretty well.
These are my results:

For CASIA1
```
                    Actual
                    Fake    Real
Predicted   Fake    71      156
            Real    729     765
```

For CASIA2
```
                    Actual
                    Fake    Real
Predicted   Fake    732     313
            Real    4391    7124
```

Here's the script which I used:
```python
import os
import sys

from HiFi_Net import HiFi_Net


HiFi = HiFi_Net()  # initialize


fake = 0
real = 0


def run():
    if len(sys.argv) != 2:
        print("Usage: python demo.py <path_to_dir>")
        sys.exit(1)

    processed = 0
    img_dir = sys.argv[1]
    for root, dirs, files in os.walk(img_dir):
        for file in files:
            filepath = os.path.join(root, file)
            ext = os.path.splitext(filepath)[-1].lower()
            if ext in {".jpg", ".jpeg", ".png", ".tiff", ".tif", ".bmp"}:
                process_file(filepath)
                processed += 1
                if processed % 100 == 0:
                    print(f"Processed {processed} images")
                    print(f"Fake: {fake}, Real: {real}")

    print(f"Processed {processed} images")
    print(f"Fake: {fake}, Real: {real}")


def process_file(img_path: str):
    global fake, real
    ## detection
    res3, prob3 = HiFi.detect(img_path, verbose=False)
    # print(res3, prob3)
    if res3 == 0:
        real += 1
    else:
        fake += 1


run()

**Comment by CHELSEA234** [comment]
Thank you very much for noticing this @lukesolo , I have only evaluated this checkpoint on the HiFi-IFDL and I will take a look on CASIA during weekend. After I find out what is going on, I will let you know!

**Comment by IApple233** [comment]
Have you resolved this issue? I have also encountered the same problem.

**Comment by CHELSEA234** [comment]
@lukesolo @IApple233 I have updated a new [section](https://github.com/CHELSEA234/HiFi_IFDL#quick-usage-on-manipulation-localization) for the localization purpose, please try it out and feel free to re-open this issue if necessary.

**Comment by CHELSEA234** [comment]
@lukesolo @IApple233  Please let me know you run into any problem.
