### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by dariogarcia** [CHELSEA234/HiFi_IFDL#5]
In order for others to reproduce or create derivative works, the repo should be assigned a permissive license. By default full prohibitive copyright applies.

**Comment by abinabrahamjohn** [comment]
Hi @CHELSEA234 , would be great to know about the licensing. Is this under the MIT license and open to usage and extensions without any restrictions?

**Comment by CHELSEA234** [comment]
@abinabrahamjohn @dariogarcia , sorry for the late reply. All contents on this github are available for the research purpose. If you want to move for licensing, then this request has to go through Michigan State University. More helps from me can be available after Nov, 11th.
