### ISSUE TITLE
Waiting for the dataset

### ISSUE THREAD

**Issue by wangyxxjtu** [CHELSEA234/HiFi_IFDL#6]
Great work, I'll keep waiting your dataset!

**Comment by laiyingxin2** [comment]
Waiting for the dataset

**Comment by sxt999** [comment]
Waiting for the dataset

**Comment by fangmq** [comment]
waiting for dataset

**Comment by 85zhanghao** [comment]
waiting for dataset,too！

**Comment by OMGGGGG** [comment]
Waiting for the dataset + 1

**Comment by CHELSEA234** [comment]
can you check out the dataset now？

**Comment by zjbthomas** [comment]
> can you check out the dataset now？

Thanks for sharing the dataset.

Just check the STGAN images and I am just wondering: for a certain image, how can we find its authentic version, modified version, and the corresponding mask? The naming of images seems confusing to me.

**Comment by wangyxxjtu** [comment]
Thank you for your sharing.

**Comment by CHELSEA234** [comment]
@zjbthomas sorry for the inconvience. before answering your question, please check the STGAN.txt in this [link](https://drive.google.com/drive/folders/1OIUv7OGxfAyerMnmKvrNnN_5CmIDcNxo?usp=sharing), which contains all manipulated/modified images we have used for training and validation. This txt file will be loaded by this line of code: https://github.com/CHELSEA234/HiFi_IFDL/blob/main/utils/load_data.py#L163. After that, I think you can understand how to find it corresponding masks. Lastly, I am not sure if I have release the authentic images, if I do not, you can simply find them in the public celebAHQ dataset.
