### ISSUE TITLE
problems with eval.py 

### ISSUE THREAD

**Issue by JPKrinsky** [CHELSEA234/HiFi_IFDL#8]
Hey, I set up the config.py and downloaded the weights from gdrive and when I run the eval.py code provided I get really odd localizations. I'm trying to run it on the Korus realistic tampered dataset which is ~220 1080x1920 TIFF images heres my code

```
from HiFi_Net import HiFi_Net 
from PIL import Image
import numpy as np
import os

HiFi = HiFi_Net()   # initialize
img_dir = 'korus/tampered/'

#   ## detection

for item in os.listdir(img_dir):
  ## localization
  full_path = os.path.join(img_dir,item)
  binary_mask = HiFi.localize(full_path)
  binary_mask = Image.fromarray((binary_mask*255.).astype(np.uint8))
  binary_mask.save(f'{item}')
```

Note: I also try running like this but replace korus/tampered with IMD2020/tampered and get similarly weird prediction maps do you have an idea of what I might be messing up?

**Comment by CHELSEA234** [comment]
@JPKrinsky , I have updated a new [section](https://github.com/CHELSEA234/HiFi_IFDL#quick-usage-on-manipulation-localization) for the localization purpose, which also includes IMD2020. the previous code is meant for HiFi-IFDL dataset performance.
